[package]
name = "nes_emu"
version = "0.1.0"
authors = ["Seth Pyle <seth.pyle86@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tui = "0.14.0"
hex = "0.4.2"
termion = "1.5.5"